secret:
  table_name: "devops-challenge"
  key: "thedoctor"
health_check:
  container: "https://hub.docker.com/r/riffo/devops-challenge"
  project: "https://github.com/riffsters/riffsters-challenge"
aws:
  region_name: "us-east-1"
